/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TraduzirRouteImport } from './routes/traduzir'
import { Route as SaudacoesRouteImport } from './routes/saudacoes'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as MusicasRouteImport } from './routes/musicas'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as DicionarioRouteImport } from './routes/dicionario'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrilhasIndexRouteImport } from './routes/trilhas.index'
import { Route as TrilhasSlugRouteImport } from './routes/trilhas.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TraduzirRoute = TraduzirRouteImport.update({
  id: '/traduzir',
  path: '/traduzir',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudacoesRoute = SaudacoesRouteImport.update({
  id: '/saudacoes',
  path: '/saudacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasRoute = MusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const DicionarioRoute = DicionarioRouteImport.update({
  id: '/dicionario',
  path: '/dicionario',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasIndexRoute = TrilhasIndexRouteImport.update({
  id: '/trilhas/',
  path: '/trilhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasSlugRoute = TrilhasSlugRouteImport.update({
  id: '/trilhas/$slug',
  path: '/trilhas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dicionario': typeof DicionarioRoute
  '/historias': typeof HistoriasRoute
  '/musicas': typeof MusicasRoute
  '/professor': typeof ProfessorRoute
  '/saudacoes': typeof SaudacoesRoute
  '/traduzir': typeof TraduzirRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/trilhas/': typeof TrilhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dicionario': typeof DicionarioRoute
  '/historias': typeof HistoriasRoute
  '/musicas': typeof MusicasRoute
  '/professor': typeof ProfessorRoute
  '/saudacoes': typeof SaudacoesRoute
  '/traduzir': typeof TraduzirRoute
  '/videos': typeof VideosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/trilhas': typeof TrilhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dicionario': typeof DicionarioRoute
  '/historias': typeof HistoriasRoute
  '/musicas': typeof MusicasRoute
  '/professor': typeof ProfessorRoute
  '/saudacoes': typeof SaudacoesRoute
  '/traduzir': typeof TraduzirRoute
  '/videos': typeof VideosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/trilhas/': typeof TrilhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dicionario'
    | '/historias'
    | '/musicas'
    | '/professor'
    | '/saudacoes'
    | '/traduzir'
    | '/videos'
    | '/admin'
    | '/trilhas/$slug'
    | '/trilhas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dicionario'
    | '/historias'
    | '/musicas'
    | '/professor'
    | '/saudacoes'
    | '/traduzir'
    | '/videos'
    | '/admin'
    | '/trilhas/$slug'
    | '/trilhas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dicionario'
    | '/historias'
    | '/musicas'
    | '/professor'
    | '/saudacoes'
    | '/traduzir'
    | '/videos'
    | '/_authenticated/admin'
    | '/trilhas/$slug'
    | '/trilhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DicionarioRoute: typeof DicionarioRoute
  HistoriasRoute: typeof HistoriasRoute
  MusicasRoute: typeof MusicasRoute
  ProfessorRoute: typeof ProfessorRoute
  SaudacoesRoute: typeof SaudacoesRoute
  TraduzirRoute: typeof TraduzirRoute
  VideosRoute: typeof VideosRoute
  TrilhasSlugRoute: typeof TrilhasSlugRoute
  TrilhasIndexRoute: typeof TrilhasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traduzir': {
      id: '/traduzir'
      path: '/traduzir'
      fullPath: '/traduzir'
      preLoaderRoute: typeof TraduzirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudacoes': {
      id: '/saudacoes'
      path: '/saudacoes'
      fullPath: '/saudacoes'
      preLoaderRoute: typeof SaudacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas': {
      id: '/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof MusicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicionario': {
      id: '/dicionario'
      path: '/dicionario'
      fullPath: '/dicionario'
      preLoaderRoute: typeof DicionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/': {
      id: '/trilhas/'
      path: '/trilhas'
      fullPath: '/trilhas/'
      preLoaderRoute: typeof TrilhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$slug': {
      id: '/trilhas/$slug'
      path: '/trilhas/$slug'
      fullPath: '/trilhas/$slug'
      preLoaderRoute: typeof TrilhasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DicionarioRoute: DicionarioRoute,
  HistoriasRoute: HistoriasRoute,
  MusicasRoute: MusicasRoute,
  ProfessorRoute: ProfessorRoute,
  SaudacoesRoute: SaudacoesRoute,
  TraduzirRoute: TraduzirRoute,
  VideosRoute: VideosRoute,
  TrilhasSlugRoute: TrilhasSlugRoute,
  TrilhasIndexRoute: TrilhasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
