/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosInfantilRouteImport } from './routes/videos-infantil'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrilhasInfantilRouteImport } from './routes/trilhas-infantil'
import { Route as TraduzirRouteImport } from './routes/traduzir'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SaudacoesRouteImport } from './routes/saudacoes'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReembolsoRouteImport } from './routes/reembolso'
import { Route as ProfessorInfantilRouteImport } from './routes/professor-infantil'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MusicasInfantilRouteImport } from './routes/musicas-infantil'
import { Route as MusicasRouteImport } from './routes/musicas'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as JogosInfantilRouteImport } from './routes/jogos-infantil'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as InfantilRouteImport } from './routes/infantil'
import { Route as HistoriasInfantilRouteImport } from './routes/historias-infantil'
import { Route as HistoriasRouteImport } from './routes/historias'
import { Route as DicionarioRouteImport } from './routes/dicionario'
import { Route as BiografiaRouteImport } from './routes/biografia'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmizadeRouteImport } from './routes/amizade'
import { Route as AdultoRouteImport } from './routes/adulto'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrilhasIndexRouteImport } from './routes/trilhas.index'
import { Route as TrilhasSlugRouteImport } from './routes/trilhas.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksPlanExpiryRouteImport } from './routes/api/public/hooks/plan-expiry'

const VideosInfantilRoute = VideosInfantilRouteImport.update({
  id: '/videos-infantil',
  path: '/videos-infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasInfantilRoute = TrilhasInfantilRouteImport.update({
  id: '/trilhas-infantil',
  path: '/trilhas-infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const TraduzirRoute = TraduzirRouteImport.update({
  id: '/traduzir',
  path: '/traduzir',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudacoesRoute = SaudacoesRouteImport.update({
  id: '/saudacoes',
  path: '/saudacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReembolsoRoute = ReembolsoRouteImport.update({
  id: '/reembolso',
  path: '/reembolso',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorInfantilRoute = ProfessorInfantilRouteImport.update({
  id: '/professor-infantil',
  path: '/professor-infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasInfantilRoute = MusicasInfantilRouteImport.update({
  id: '/musicas-infantil',
  path: '/musicas-infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicasRoute = MusicasRouteImport.update({
  id: '/musicas',
  path: '/musicas',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosInfantilRoute = JogosInfantilRouteImport.update({
  id: '/jogos-infantil',
  path: '/jogos-infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const InfantilRoute = InfantilRouteImport.update({
  id: '/infantil',
  path: '/infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasInfantilRoute = HistoriasInfantilRouteImport.update({
  id: '/historias-infantil',
  path: '/historias-infantil',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasRoute = HistoriasRouteImport.update({
  id: '/historias',
  path: '/historias',
  getParentRoute: () => rootRouteImport,
} as any)
const DicionarioRoute = DicionarioRouteImport.update({
  id: '/dicionario',
  path: '/dicionario',
  getParentRoute: () => rootRouteImport,
} as any)
const BiografiaRoute = BiografiaRouteImport.update({
  id: '/biografia',
  path: '/biografia',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmizadeRoute = AmizadeRouteImport.update({
  id: '/amizade',
  path: '/amizade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultoRoute = AdultoRouteImport.update({
  id: '/adulto',
  path: '/adulto',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasIndexRoute = TrilhasIndexRouteImport.update({
  id: '/trilhas/',
  path: '/trilhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhasSlugRoute = TrilhasSlugRouteImport.update({
  id: '/trilhas/$slug',
  path: '/trilhas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPlanExpiryRoute =
  ApiPublicHooksPlanExpiryRouteImport.update({
    id: '/api/public/hooks/plan-expiry',
    path: '/api/public/hooks/plan-expiry',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/adulto': typeof AdultoRoute
  '/amizade': typeof AmizadeRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/biografia': typeof BiografiaRoute
  '/dicionario': typeof DicionarioRoute
  '/historias': typeof HistoriasRoute
  '/historias-infantil': typeof HistoriasInfantilRoute
  '/infantil': typeof InfantilRoute
  '/instalar': typeof InstalarRoute
  '/jogos': typeof JogosRoute
  '/jogos-infantil': typeof JogosInfantilRoute
  '/minha-conta': typeof MinhaContaRoute
  '/musicas': typeof MusicasRoute
  '/musicas-infantil': typeof MusicasInfantilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRoute
  '/professor-infantil': typeof ProfessorInfantilRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saudacoes': typeof SaudacoesRoute
  '/termos': typeof TermosRoute
  '/traduzir': typeof TraduzirRoute
  '/trilhas-infantil': typeof TrilhasInfantilRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/videos': typeof VideosRoute
  '/videos-infantil': typeof VideosInfantilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/trilhas/': typeof TrilhasIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/plan-expiry': typeof ApiPublicHooksPlanExpiryRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/adulto': typeof AdultoRoute
  '/amizade': typeof AmizadeRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/biografia': typeof BiografiaRoute
  '/dicionario': typeof DicionarioRoute
  '/historias': typeof HistoriasRoute
  '/historias-infantil': typeof HistoriasInfantilRoute
  '/infantil': typeof InfantilRoute
  '/instalar': typeof InstalarRoute
  '/jogos': typeof JogosRoute
  '/jogos-infantil': typeof JogosInfantilRoute
  '/minha-conta': typeof MinhaContaRoute
  '/musicas': typeof MusicasRoute
  '/musicas-infantil': typeof MusicasInfantilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRoute
  '/professor-infantil': typeof ProfessorInfantilRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saudacoes': typeof SaudacoesRoute
  '/termos': typeof TermosRoute
  '/traduzir': typeof TraduzirRoute
  '/trilhas-infantil': typeof TrilhasInfantilRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/videos': typeof VideosRoute
  '/videos-infantil': typeof VideosInfantilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/trilhas': typeof TrilhasIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/plan-expiry': typeof ApiPublicHooksPlanExpiryRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/adulto': typeof AdultoRoute
  '/amizade': typeof AmizadeRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/biografia': typeof BiografiaRoute
  '/dicionario': typeof DicionarioRoute
  '/historias': typeof HistoriasRoute
  '/historias-infantil': typeof HistoriasInfantilRoute
  '/infantil': typeof InfantilRoute
  '/instalar': typeof InstalarRoute
  '/jogos': typeof JogosRoute
  '/jogos-infantil': typeof JogosInfantilRoute
  '/minha-conta': typeof MinhaContaRoute
  '/musicas': typeof MusicasRoute
  '/musicas-infantil': typeof MusicasInfantilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/professor': typeof ProfessorRoute
  '/professor-infantil': typeof ProfessorInfantilRoute
  '/reembolso': typeof ReembolsoRoute
  '/reset-password': typeof ResetPasswordRoute
  '/saudacoes': typeof SaudacoesRoute
  '/termos': typeof TermosRoute
  '/traduzir': typeof TraduzirRoute
  '/trilhas-infantil': typeof TrilhasInfantilRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/videos': typeof VideosRoute
  '/videos-infantil': typeof VideosInfantilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/trilhas/$slug': typeof TrilhasSlugRoute
  '/trilhas/': typeof TrilhasIndexRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/plan-expiry': typeof ApiPublicHooksPlanExpiryRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/adulto'
    | '/amizade'
    | '/auth'
    | '/bem-vindo'
    | '/biografia'
    | '/dicionario'
    | '/historias'
    | '/historias-infantil'
    | '/infantil'
    | '/instalar'
    | '/jogos'
    | '/jogos-infantil'
    | '/minha-conta'
    | '/musicas'
    | '/musicas-infantil'
    | '/planos'
    | '/privacidade'
    | '/professor'
    | '/professor-infantil'
    | '/reembolso'
    | '/reset-password'
    | '/saudacoes'
    | '/termos'
    | '/traduzir'
    | '/trilhas-infantil'
    | '/unsubscribe'
    | '/videos'
    | '/videos-infantil'
    | '/admin'
    | '/email/unsubscribe'
    | '/trilhas/$slug'
    | '/trilhas/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/plan-expiry'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/adulto'
    | '/amizade'
    | '/auth'
    | '/bem-vindo'
    | '/biografia'
    | '/dicionario'
    | '/historias'
    | '/historias-infantil'
    | '/infantil'
    | '/instalar'
    | '/jogos'
    | '/jogos-infantil'
    | '/minha-conta'
    | '/musicas'
    | '/musicas-infantil'
    | '/planos'
    | '/privacidade'
    | '/professor'
    | '/professor-infantil'
    | '/reembolso'
    | '/reset-password'
    | '/saudacoes'
    | '/termos'
    | '/traduzir'
    | '/trilhas-infantil'
    | '/unsubscribe'
    | '/videos'
    | '/videos-infantil'
    | '/admin'
    | '/email/unsubscribe'
    | '/trilhas/$slug'
    | '/trilhas'
    | '/lovable/email/suppression'
    | '/api/public/hooks/plan-expiry'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso-negado'
    | '/adulto'
    | '/amizade'
    | '/auth'
    | '/bem-vindo'
    | '/biografia'
    | '/dicionario'
    | '/historias'
    | '/historias-infantil'
    | '/infantil'
    | '/instalar'
    | '/jogos'
    | '/jogos-infantil'
    | '/minha-conta'
    | '/musicas'
    | '/musicas-infantil'
    | '/planos'
    | '/privacidade'
    | '/professor'
    | '/professor-infantil'
    | '/reembolso'
    | '/reset-password'
    | '/saudacoes'
    | '/termos'
    | '/traduzir'
    | '/trilhas-infantil'
    | '/unsubscribe'
    | '/videos'
    | '/videos-infantil'
    | '/_authenticated/admin'
    | '/email/unsubscribe'
    | '/trilhas/$slug'
    | '/trilhas/'
    | '/lovable/email/suppression'
    | '/api/public/hooks/plan-expiry'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AdultoRoute: typeof AdultoRoute
  AmizadeRoute: typeof AmizadeRoute
  AuthRoute: typeof AuthRoute
  BemVindoRoute: typeof BemVindoRoute
  BiografiaRoute: typeof BiografiaRoute
  DicionarioRoute: typeof DicionarioRoute
  HistoriasRoute: typeof HistoriasRoute
  HistoriasInfantilRoute: typeof HistoriasInfantilRoute
  InfantilRoute: typeof InfantilRoute
  InstalarRoute: typeof InstalarRoute
  JogosRoute: typeof JogosRoute
  JogosInfantilRoute: typeof JogosInfantilRoute
  MinhaContaRoute: typeof MinhaContaRoute
  MusicasRoute: typeof MusicasRoute
  MusicasInfantilRoute: typeof MusicasInfantilRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProfessorRoute: typeof ProfessorRoute
  ProfessorInfantilRoute: typeof ProfessorInfantilRoute
  ReembolsoRoute: typeof ReembolsoRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaudacoesRoute: typeof SaudacoesRoute
  TermosRoute: typeof TermosRoute
  TraduzirRoute: typeof TraduzirRoute
  TrilhasInfantilRoute: typeof TrilhasInfantilRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VideosRoute: typeof VideosRoute
  VideosInfantilRoute: typeof VideosInfantilRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  TrilhasSlugRoute: typeof TrilhasSlugRoute
  TrilhasIndexRoute: typeof TrilhasIndexRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksPlanExpiryRoute: typeof ApiPublicHooksPlanExpiryRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos-infantil': {
      id: '/videos-infantil'
      path: '/videos-infantil'
      fullPath: '/videos-infantil'
      preLoaderRoute: typeof VideosInfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas-infantil': {
      id: '/trilhas-infantil'
      path: '/trilhas-infantil'
      fullPath: '/trilhas-infantil'
      preLoaderRoute: typeof TrilhasInfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traduzir': {
      id: '/traduzir'
      path: '/traduzir'
      fullPath: '/traduzir'
      preLoaderRoute: typeof TraduzirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saudacoes': {
      id: '/saudacoes'
      path: '/saudacoes'
      fullPath: '/saudacoes'
      preLoaderRoute: typeof SaudacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reembolso': {
      id: '/reembolso'
      path: '/reembolso'
      fullPath: '/reembolso'
      preLoaderRoute: typeof ReembolsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor-infantil': {
      id: '/professor-infantil'
      path: '/professor-infantil'
      fullPath: '/professor-infantil'
      preLoaderRoute: typeof ProfessorInfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas-infantil': {
      id: '/musicas-infantil'
      path: '/musicas-infantil'
      fullPath: '/musicas-infantil'
      preLoaderRoute: typeof MusicasInfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musicas': {
      id: '/musicas'
      path: '/musicas'
      fullPath: '/musicas'
      preLoaderRoute: typeof MusicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos-infantil': {
      id: '/jogos-infantil'
      path: '/jogos-infantil'
      fullPath: '/jogos-infantil'
      preLoaderRoute: typeof JogosInfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infantil': {
      id: '/infantil'
      path: '/infantil'
      fullPath: '/infantil'
      preLoaderRoute: typeof InfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias-infantil': {
      id: '/historias-infantil'
      path: '/historias-infantil'
      fullPath: '/historias-infantil'
      preLoaderRoute: typeof HistoriasInfantilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias': {
      id: '/historias'
      path: '/historias'
      fullPath: '/historias'
      preLoaderRoute: typeof HistoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dicionario': {
      id: '/dicionario'
      path: '/dicionario'
      fullPath: '/dicionario'
      preLoaderRoute: typeof DicionarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biografia': {
      id: '/biografia'
      path: '/biografia'
      fullPath: '/biografia'
      preLoaderRoute: typeof BiografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amizade': {
      id: '/amizade'
      path: '/amizade'
      fullPath: '/amizade'
      preLoaderRoute: typeof AmizadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adulto': {
      id: '/adulto'
      path: '/adulto'
      fullPath: '/adulto'
      preLoaderRoute: typeof AdultoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/': {
      id: '/trilhas/'
      path: '/trilhas'
      fullPath: '/trilhas/'
      preLoaderRoute: typeof TrilhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilhas/$slug': {
      id: '/trilhas/$slug'
      path: '/trilhas/$slug'
      fullPath: '/trilhas/$slug'
      preLoaderRoute: typeof TrilhasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/plan-expiry': {
      id: '/api/public/hooks/plan-expiry'
      path: '/api/public/hooks/plan-expiry'
      fullPath: '/api/public/hooks/plan-expiry'
      preLoaderRoute: typeof ApiPublicHooksPlanExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AdultoRoute: AdultoRoute,
  AmizadeRoute: AmizadeRoute,
  AuthRoute: AuthRoute,
  BemVindoRoute: BemVindoRoute,
  BiografiaRoute: BiografiaRoute,
  DicionarioRoute: DicionarioRoute,
  HistoriasRoute: HistoriasRoute,
  HistoriasInfantilRoute: HistoriasInfantilRoute,
  InfantilRoute: InfantilRoute,
  InstalarRoute: InstalarRoute,
  JogosRoute: JogosRoute,
  JogosInfantilRoute: JogosInfantilRoute,
  MinhaContaRoute: MinhaContaRoute,
  MusicasRoute: MusicasRoute,
  MusicasInfantilRoute: MusicasInfantilRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProfessorRoute: ProfessorRoute,
  ProfessorInfantilRoute: ProfessorInfantilRoute,
  ReembolsoRoute: ReembolsoRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaudacoesRoute: SaudacoesRoute,
  TermosRoute: TermosRoute,
  TraduzirRoute: TraduzirRoute,
  TrilhasInfantilRoute: TrilhasInfantilRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VideosRoute: VideosRoute,
  VideosInfantilRoute: VideosInfantilRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  TrilhasSlugRoute: TrilhasSlugRoute,
  TrilhasIndexRoute: TrilhasIndexRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksPlanExpiryRoute: ApiPublicHooksPlanExpiryRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
