DELETE FROM public.dictionary WHERE example LIKE '[curado-2015]%';
INSERT INTO public.dictionary (term_indigenous, term_pt, language, category, pronunciation, example) VALUES
('akxãy','Olá / Oi','Patxôhã','Saudações','a-kxã-y','[curado-2015] Significado: Saudação simples e aberta para qualquer momento • Uso: Ao chegar ou chamar atenção suavemente'),
('hayôkunã','Bom dia','Patxôhã','Saudações','ha-yô-ku-nã','[curado-2015] Significado: Desejo de bom caminho sob o sol que nasce • Uso: Usado até por volta do meio-dia • Variantes/Formas: Resposta: hayôxó'),
('ῖtxê niató','Boa tarde','Patxôhã','Saudações','ĩ-txê ni-a-tó','[curado-2015] Significado: Acolhimento quando o sol já desce • Uso: Do meio-dia até antes do entardecer • Variantes/Formas: Resposta: miriaú'),
('akunã','Boa noite','Patxôhã','Saudações','a-ku-nã','[curado-2015] Significado: Proteção e descanso sob o céu estrelado • Uso: Ao entardecer ou antes de dormir • Variantes/Formas: Despedida: bolukunã / ῖtxê hamôp'),
('dawê','Adeus','Patxôhã','Saudações','da-wê','[curado-2015] Significado: Vai com cuidado, nos encontramos novamente • Uso: Quando se afasta por tempo maior'),
('ikôtxeká','Por favor','Patxôhã','Saudações','i-kô-txe-ká','[curado-2015] Significado: Peço com respeito e confiança • Uso: Antes de pedir algo ou ajuda'),
('hũtxeká','Com licença','Patxôhã','Saudações','hũ-txe-ká','[curado-2015] Significado: Passo ou falo sem invadir espaço alheio • Uso: Ao entrar, passar na frente ou interromper'),
('hũnänãy / poytã','Desculpa / Perdão','Patxôhã','Saudações','hũ-nã-nãy / poy-tã','[curado-2015] Significado: Reconheço e desejo voltar ao bom convívio • Uso: Quando erra ou incomoda sem querer'),
('hã','Sim','Patxôhã','Saudações','hã','[curado-2015] Significado: Concordo, aceito, estou junto • Uso: Curto e firme, sem pressa'),
('ãhô','Não','Patxôhã','Saudações','ã-hô','[curado-2015] Significado: Não é assim, mas sem brigar • Uso: Dito suavemente, com respeito'),
('yamã / awêry','Obrigado / Gratidão','Patxôhã','Saudações','ya-mã / a-wê-ry','[curado-2015] Significado: Reconhecer o bem recebido • Uso: Presente em todas as relações • Variantes/Formas: Relaciona-se ao Awê — amor-união'),
('ahõhê','Tudo bem? / Como vai?','Patxôhã','Saudações','a-hõ-hê','[curado-2015] Significado: Quero saber se está bem e forte • Uso: Contato mais próximo e amigo'),
('ihã atêkuã','Até amanhã','Patxôhã','Saudações','i-hã a-tê-ku-ã','[curado-2015] Significado: Nos vemos quando o sol voltar • Uso: Despedida ao fim do dia'),
('txuhap','Vamos / Vamos lá','Patxôhã','Saudações','txu-hap','[curado-2015] Significado: Seguimos juntos, ninguém fica para trás • Uso: Chamada para caminhar, trabalhar ou ir ao ritual • Variantes/Formas: Variantes: txuhab / ahĩkábm'),
('kakusú','Homem','Patxôhã','Família','ka-ku-sú','[curado-2015] Significado: Ser forte, responsável por proteger e manter • Uso: Distinção entre solteiro e constituído • Variantes/Formas: Casado: kakuseká'),
('jokana','Mulher','Patxôhã','Família','jo-ka-na','[curado-2015] Significado: Portadora da vida, guardiã da palavra e do alimento • Uso: Também marca passagem de fase na vida • Variantes/Formas: Solteira: ãko'),
('ipamakã','Pai','Patxôhã','Família','i-pa-ma-kã','[curado-2015] Significado: Quem ensina o caminho da força e decisão coletiva • Uso: Presença forte nas decisões familiares • Variantes/Formas: Adotivo: kaponetú'),
('imakã','Mãe','Patxôhã','Família','i-ma-kã','[curado-2015] Significado: Primeira escola: língua, histórias e respeito • Uso: Cuida da saúde, alimentação e harmonia do lar • Variantes/Formas: Madrasta: ekäi'),
('konehõ','Filho / Criança','Patxôhã','Família','ko-ne-hõ','[curado-2015] Significado: Semente nova, esperança e continuidade do povo • Uso: Desde pequeno participa de brincadeiras-ensino • Variantes/Formas: Menino: kitok | Menina: kuhukê'),
('kehetohê','Avô','Patxôhã','Família','ke-he-to-hê','[curado-2015] Significado: Banco de memória, guardião das histórias antigas • Uso: Respeito maior entre todos da aldeia'),
('niõtxi','Avó','Patxôhã','Família','ni-õ-txi','[curado-2015] Significado: Ensina a arte de viver bem, cozinhar e curar • Uso: Referência feminina principal da sabedoria'),
('inã','Irmão','Patxôhã','Família','i-nã','[curado-2015] Significado: Companheiro de vida, igual a si mesmo • Uso: Idade define função e respeito • Variantes/Formas: Mais velho: eketãnay | Mais novo: ahuy'),
('itehema','Irmã','Patxôhã','Família','i-te-he-ma','[curado-2015] Significado: Ligação especial, partilha de segredos e cuidados • Uso: Crescem aprendendo os papéis juntas • Variantes/Formas: Adotiva: hemãkô'),
('akâié','Chefe / Cacique','Patxôhã','Família','a-kâ-i-é','[curado-2015] Significado: Quem ouve primeiro todos, depois fala e decide • Uso: Preside cerimônias e resoluções • Variantes/Formas: Principal: akâiéko'),
('ĩgihòbòku','Pajé','Patxôhã','Família','ĩ-gi-hò-bò-ku','[curado-2015] Significado: Conhece segredos do corpo, da alma e da floresta • Uso: Cuida da saúde espiritual e equilíbrio'),
('hitap','Ancião','Patxôhã','Família','hi-tap','[curado-2015] Significado: Quantidade de conhecimento acumulado • Uso: Sua palavra tem peso maior em assembleia • Variantes/Formas: Homem velho: ĩpámakiame'),
('makínã','Pessoa / Povo','Patxôhã','Família','ma-kí-nã','[curado-2015] Significado: Todos juntos formam força maior • Uso: Identidade coletiva: somos um corpo só • Variantes/Formas: Variante: muhutí'),
('hãhão','Terra / Chão','Patxôhã','Natureza','hã-hão','[curado-2015] Significado: Mãe maior: corpo onde todos vivemos • Uso: Base de tudo — roçado, casa, caminho • Variantes/Formas: Seca: hamotxê | Var: hãhãw'),
('miãga','Água','Patxôhã','Natureza','mi-ã-ga','[curado-2015] Significado: Sangue da terra, traz vida e purifica • Uso: Presente em rituais essenciais • Variantes/Formas: Var: txonãg / úna''ã | Chuva: txiäng'),
('hayô','Sol / Luz','Patxôhã','Natureza','ha-yô','[curado-2015] Significado: Primeiro parente: traz força, calor e tempo • Uso: Marca horários do dia • Variantes/Formas: Var: mayõ'),
('joôpek','Fogo','Patxôhã','Natureza','jo-ô-pek','[curado-2015] Significado: Mensageiro: fumaça leva nossa palavra ao céu • Uso: Essencial no Ritual da Chuva • Variantes/Formas: Var: txahab | Pequeno: joôpek''kwi'),
('hãtsá''i','Ar / Vento','Patxôhã','Natureza','hã-tsá-i','[curado-2015] Significado: Respiração do mundo: leva sons e avisos • Uso: No Tohé representa movimento • Variantes/Formas: Var: kuypô'),
('itohã','Céu','Patxôhã','Natureza','i-to-hã','[curado-2015] Significado: Teto grande, onde moram antepassados • Uso: Direção sagrada nas orações'),
('tehé','Chuva','Patxôhã','Natureza','te-hé','[curado-2015] Significado: Presente da água que renova a terra • Uso: Ritual para pedir e agradecer • Variantes/Formas: Tempestade: potehé'),
('kamarú','Árvore / Madeira','Patxôhã','Natureza','ka-ma-rú','[curado-2015] Significado: Ser vivo, guardião da sombra • Uso: Material para casa, ferramenta, grafismo • Variantes/Formas: Var: niotxikajo | Trabalhada: pajarú'),
('kekatxá','Rio','Patxôhã','Natureza','ke-ka-txá','[curado-2015] Significado: Caminho líquido que nunca para • Uso: Lugar de encontro, pesca, banho • Variantes/Formas: Riacho: gãry'),
('ĩbá','Mata / Floresta','Patxôhã','Natureza','ĩ-bá','[curado-2015] Significado: Casa grande onde vivem todas as vozes • Uso: Fonte de remédios, frutos, caça • Variantes/Formas: Var: tokoutka | Fechada: maturẽbá'),
('baway','Pedra','Patxôhã','Natureza','ba-way','[curado-2015] Significado: O mais velho: esteve aqui antes de nós • Uso: Símbolo de força, firmeza • Variantes/Formas: Var: míkay | Preciosa: biáy'),
('pataxi','Aldeia','Patxôhã','Natureza','pa-ta-xi','[curado-2015] Significado: Lugar onde a palavra Pataxó continua viva • Uso: Organizada em círculo, ninguém fica fora • Variantes/Formas: Var: kijẽmi | Reunião: tapave'),
('kuké','Cachorro','Patxôhã','Animais','ku-ké','[curado-2015] Significado: Primeiro amigo que veio morar na aldeia • Uso: Guarda, avisa e acompanha caçadas • Variantes/Formas: Do mato: bue'),
('hemũgãy','Onça','Patxôhã','Animais','he-mũ-gãy','[curado-2015] Significado: Grande senhora da floresta: força e astúcia • Uso: Presente em histórias antigas • Variantes/Formas: Fêmea: áxiná | Preta: kuparaka'),
('mãnãy','Veado','Patxôhã','Animais','mã-nãy','[curado-2015] Significado: Leve, rápido e atento: caminhada certa • Uso: Carne, pele e chifres para artesanato • Variantes/Formas: Mateiro: kamusika'),
('amatxi','Anta','Patxôhã','Animais','a-ma-txi','[curado-2015] Significado: Maior habitante da terra firme • Uso: Preserva caminhos que abre na mata • Variantes/Formas: Fêmea: hamahay'),
('mmai','Jacaré','Patxôhã','Animais','m-mai','[curado-2015] Significado: Guarda das águas profundas • Uso: Respeitado, não caçado sem motivo'),
('ãkopa','Pássaro','Patxôhã','Animais','ã-ko-pa','[curado-2015] Significado: Mensageiro: traz notícias do céu • Uso: Cada canto tem significado próprio • Variantes/Formas: Var: pàkây | Beija-flor: guanãbi | Tucano: ẽháy'),
('mukusuy','Peixe','Patxôhã','Animais','mu-ku-suy','[curado-2015] Significado: Parente que vive dentro da água • Uso: Alimento principal vindo do rio • Variantes/Formas: De rio: mahãm'),
('kayñãdura','Cobra','Patxôhã','Animais','kay-ñã-du-ra','[curado-2015] Significado: Conhece segredos do chão, renasce trocando pele • Uso: Sinal de alerta e respeito máximo • Variantes/Formas: Jararaca: añá | Sucuri: añá''voë'),
('p''ap''ai','Abelha','Patxôhã','Animais','p''a-p''ai','[curado-2015] Significado: Trabalha junta, faz mel e cera • Uso: Nunca destruir casa delas • Variantes/Formas: Var: pâpây | Preta: pagnõ'),
('poniohõ','Macaco','Patxôhã','Animais','po-ni-o-hõ','[curado-2015] Significado: Brincalhão e esperto • Uso: Conta histórias engraçadas • Variantes/Formas: Espécies: apkí / bĩkĩ''ú'),
('ãpekôy','Corpo','Patxôhã','Corpo','ã-pe-kô-y','[curado-2015] Significado: Casa onde vive nossa alma • Uso: Tratado com respeito, leva marca da cultura • Variantes/Formas: Masculino: kovekoy | Feminino: kuidã'),
('kôkuã','Cabeça','Patxôhã','Corpo','kô-ku-ã','[curado-2015] Significado: Pensamento, memória e palavra saem daqui • Uso: Primeiro lugar da pintura sagrada • Variantes/Formas: Pequena: kôkuã''kwi | Grande: kôkuã''puá'),
('ãgwá','Olho','Patxôhã','Corpo','ã-gwá','[curado-2015] Significado: Janela: ver é reconhecer e respeitar • Uso: Nos grafismos representa vigilância'),
('pahab','Mão','Patxôhã','Corpo','pa-hab','[curado-2015] Significado: Faz, constrói, toca, acolhe, dá • Uso: Essencial nos gestos de união • Variantes/Formas: Palma: pahamenãy'),
('ãpaká','Pé','Patxôhã','Corpo','ã-pa-ká','[curado-2015] Significado: Raiz que anda: conecta corpo à terra • Uso: Base nas danças do Tohé e Awê • Variantes/Formas: Sola: niomenãy'),
('kawatá','Coração','Patxôhã','Corpo','ka-wa-tá','[curado-2015] Significado: Centro interno: sentimento verdadeiro • Uso: Relaciona-se ao Awê — amor e união'),
('a''atxu','Alma / Espírito','Patxôhã','Corpo','a''-a-txu','[curado-2015] Significado: Parte que não morre: viaja e aprende • Uso: Separa-se um pouco durante sonhos'),
('kuhú','Andar','Patxôhã','Verbos','ku-hú','[curado-2015] Significado: Mover-se mantendo contato e respeito ao solo • Uso: Seguir caminho certo da tradição • Variantes/Formas: Eu: kuhú''xó | Pass: kuhú''ã | Fut: kuhú''ĩ | Ger: kuhú''irá'),
('areneá','Falar','Patxôhã','Verbos','a-re-ne-á','[curado-2015] Significado: Usar palavra com cuidado: ela tem força própria • Uso: Fala-se devagar, ouvindo antes • Variantes/Formas: Eu: areneá''xó | Pass: areneá''ã | Fut: areneá''ĩ'),
('mãgutá','Comer','Patxôhã','Verbos','mã-gu-tá','[curado-2015] Significado: Receber força que a terra preparou • Uso: Nunca come sem agradecer • Variantes/Formas: Var: oknikenãg | Eu: mãgutá''xó | Pass: mãgutã | Fut: mãgutá''ĩ'),
('muhũ','Dormir','Patxôhã','Verbos','mu-hũ','[curado-2015] Significado: Descanso onde alma viaja buscar ensinamentos • Uso: Segue ritmo natural do sol • Variantes/Formas: Eu: muhũ''xó | Pass: muhũ''ã | Fut: muhũ''ĩ'),
('hamiá','Dançar (Tohé)','Patxôhã','Verbos','ha-mi-á','[curado-2015] Significado: Não é só movimento: é oração e união • Uso: Ritual coletivo mais importante • Variantes/Formas: Eu: hamiá''xó | Pass: hamiá''ã | Fut: hamiá''ĩ'),
('dxê','Ver / Enxergar','Patxôhã','Verbos','dx-ê','[curado-2015] Significado: Compreender também sentido oculto • Uso: Olhar diferente de só apontar olhos • Variantes/Formas: Eu: dxê''xó | Pass: dxê''ã | Fut: dxê''ĩ'),
('patxitxá','Fazer / Criar / Trabalhar','Patxôhã','Verbos','pat-xi-txá','[curado-2015] Significado: Transformar matéria sem destruir a ordem natural • Uso: Trabalho coletivo tem mais valor • Variantes/Formas: Eu: patxitxá''xó | Pass: patxitxá''ã | Fut: patxitxá''ĩ'),
('txuk','Ir / Seguir','Patxôhã','Verbos','txuk','[curado-2015] Significado: Mover-se com destino e respeito ao caminho • Uso: Oposto de vir / chegar • Variantes/Formas: Eu: txuk''xó | Pass: kohô / kuhô | Fut: txuk''ĩ'),
('mõpõy','Amar / Querer bem','Patxôhã','Verbos','mõ-põ-y','[curado-2015] Significado: Raiz do que se torna Awê — união total • Uso: Amar pessoa, terra e tudo que existe • Variantes/Formas: Eu: mõpõy''xó | Pass: mõpõy''ã | Fut: mõpõy''ĩ'),
('apetxienã','Um','Patxôhã','Números','a-pe-txie-nã','[curado-2015] Significado: Começo, unidade, tudo junto como uma coisa só • Uso: Primeiro número registrado • Variantes/Formas: Var: nioniêmã'),
('txiãgá','Branco','Patxôhã','Cores','txi-ã-gá','[curado-2015] Significado: Cor da luz, da pureza, do que está limpo • Uso: Pintura, penas e símbolos de paz'),
('tapayñũ','Preto','Patxôhã','Cores','ta-pay-ñũ','[curado-2015] Significado: Cor do cabelo, terra rica, noite profunda • Uso: Base forte nos grafismos • Variantes/Formas: Var: ĩgorá'),
('eoató','Vermelho','Patxôhã','Cores','e-o-a-tó','[curado-2015] Significado: Cor do sangue, da vida, do fogo • Uso: Principal cor cerimonial: vem do urucum • Variantes/Formas: Escuro: eoató''puá | Claro: eoató''kwi'),
('ajú','Amarelo','Patxôhã','Cores','a-jú','[curado-2015] Significado: Cor do sol maduro, frutas e flores • Uso: Extraído de plantas e argilas'),
('obi','Azul','Patxôhã','Cores','o-bi','[curado-2015] Significado: Cor do céu limpo e águas profundas • Uso: Representa estabilidade e imensidão'),
('tará','Verde','Patxôhã','Cores','ta-rá','[curado-2015] Significado: Cor da folha nova, da floresta que renova • Uso: Sempre relacionado à saúde e vida'),
('baktxi','Abacaxi','Patxôhã','Alimentos','bak-txi','[curado-2015] Significado: Fruto forte por fora, doce por dentro • Uso: Consumido maduro ou assado • Variantes/Formas: Plantação: baktxê'),
('tapitá','Banana','Patxôhã','Alimentos','ta-pi-tá','[curado-2015] Significado: Fácil de cultivar, sempre tem na aldeia • Uso: Comida de criança, doente e trabalho • Variantes/Formas: Da terra: keb''ka | Verde: kitapitá'),
('mukunã','Mandioca','Patxôhã','Alimentos','mu-ku-nã','[curado-2015] Significado: Raiz principal: base de farinha, beiju, massa • Uso: Primeira plantada em cada nova roça • Variantes/Formas: Braba: kohõ | Doce: ohóy'),
('patxiõ','Milho','Patxôhã','Alimentos','pat-xi-õ','[curado-2015] Significado: Presente em rituais, festas e oferendas • Uso: História própria da origem • Variantes/Formas: Var: b''ahob'),
('kumãdá','Feijão','Patxôhã','Alimentos','ku-mã-dá','[curado-2015] Significado: Companheiro inseparável do milho e mandioca • Uso: Sempre combina com farinha • Variantes/Formas: Preto: ahábm | Andu: nahão | Corda: kavãg'),
('kanurú','Urucum','Patxôhã','Alimentos','ka-nu-rú','[curado-2015] Significado: Planta-cor: corante vermelho natural sagrado • Uso: Pintura corporal e grafismos'),
('mĩâb','Cana-de-açúcar','Patxôhã','Alimentos','mĩ-âb','[curado-2015] Significado: Planta doce, alta e forte • Uso: Caldos, bebidas e preparos medicinais • Variantes/Formas: Açúcar refinado: merkí'),
('ãgoyrã','Abóbora','Patxôhã','Alimentos','ã-go-y-rã','[curado-2015] Significado: Fruto grande, carne macia e saborosa • Uso: Sopa, cozido, assado');